groups:
  - name: GNN-Services
    rules:
      # Alerta de servicio caído
      - alert: ServiceDown
        expr: up == 0
        for: 30s
        labels:
          severity: critical
        annotations:
          summary: "Servicio caído: {{ $labels.instance }}"
          description: "El servicio {{ $labels.instance }} lleva caído al menos 30 segundos."

      # Alerta de latencia alta (percentil 95 > 200ms)
      - alert: HighLatency
        expr: |
          histogram_quantile(0.95, rate(http_server_requests_seconds_bucket{uri="/score"}[5m])) > 0.2
        for: 1m
        labels:
          severity: warning
        annotations:
          summary: "Latencia alta en {{ $labels.instance }}"
          description: "El servicio {{ $labels.instance }} está experimentando latencias >200ms en el p95 durante el último minuto"

      # Alerta de tasa de errores alta (>5%)
      - alert: HighErrorRate
        expr: |
          sum(rate(http_server_requests_seconds_count{status=~"5.."}[5m])) by (instance) 
          / 
          sum(rate(http_server_requests_seconds_count[5m])) by (instance) > 0.05
        for: 1m
        labels:
          severity: warning
        annotations:
          summary: "Tasa de errores alta en {{ $labels.instance }}"
          description: "El servicio {{ $labels.instance }} tiene una tasa de errores >5% en el último minuto"