global:
  scrape_interval: 15s
  evaluation_interval: 15s

# Reglas de alerta
rule_files:
  - alerts.yml

# Configuración de scraping
scrape_configs:
  # Servicio Python
  - job_name: 'python-service'
    scrape_interval: 5s
    metrics_path: '/metrics'
    static_configs:
      - targets: ['python-service:9443']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'python-service'

  # Servicio Java
  - job_name: 'java-service'
    scrape_interval: 5s
    metrics_path: '/q/metrics'
    static_configs:
      - targets: ['java-service:9444']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'java-service'

  # Self-monitoring
  - job_name: 'prometheus'
    scrape_interval: 10s
    static_configs:
      - targets: ['localhost:9090']